handle = "example-us"
label = "example.com"
icon = "example-channel-icon.svg"
productFeedManagement = "automatic"

[capabilities]
bundles = true
digitalProducts = true
subscriptions = false
combinedListings = true
unlistedProducts = true

[requirements]
webPresence = false
orderInsertion = true

[[countries]]
code = "US"
languages = [
  "en"
]
currency = "USD"