handle = "example-us"
label = "example.com"
productFeedManagement = "automatic"

[capabilities]
bundles = true
digitalProducts = true
subscriptions = false
combinedListings = true
unlistedProducts = true

[requirements]
webPresence = true
orderInsertion = false

[[countries]]
code = "US"
languages = [
  "en"
]
currency = "USD"
